### ISSUE TITLE
Wondering

### ISSUE THREAD

**Issue by DarthRevanXX** [nospaceships/node-asn1-ber#18]
Can I decode ber file via your package? If yes, can you give me an example sir, please

**Comment by stephenwvickers** [comment]
I believe you can, simply read the using the `fs` module, then use this module to parse the corresponding buffer, e.g.:

```
var buffer = fs.readFileSync("...")

var reader = new asn1.BerReader(buffer)

// Now parse the file as per your protocol/semantics...
reader.readSequence()
...
```
